version: "3"
services:
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    ports:
      - "8880:8880"
      # - "9000:9000"
      # - "443:443"
    volumes:
      - ./app:/app
    command:
      - /bin/bash
      - -c
      - |
        cd /app && npm install && npm start

    # links:
      # - app
    # restart: always

