version: "3"
services:
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    ports:
      - "833:833"
      # - "9000:9000"
      # - "443:443"
    volumes:
      - ./app:/var/www/html
    # links:
      # - app
    # restart: always

